### ISSUE TITLE
Bemenet rotation

### ISSUE THREAD

**Issue by zsotroav** [Gilgames32/kbpr-ps#1]
**A probléma, mely felvetette az ötletet**
Fekvő kép bemenet kiválasztásakor átforgatja és elnyújtja magától állóba a képet.

**A megoldásod, ötleteid**
Fekvő bemenet autómatikus észlelése és korrigálása, vagy egy manuális toggle 90°-os forgatásra

**Miért lenne jó?**
Nem kell importálás előtt elforgatni, sokkal kényelmesebb lenne

**Comment by Gilgames32** [comment]
https://github.com/Gilgames32/kbpr-ps/commit/332e0a7c06a551b5b2573f0b3cac9cc652cbe459 commitban javítva.
