### ISSUE TITLE
Paper size mismatch

### ISSUE THREAD

**Issue by Bende126** [Gilgames32/kbpr-ps#17]
**A probléma, mely felvetette az ötletet**
Miért nagyít a nyomtatós progi?
![Képernyőkép 2024-10-01 145833](https://github.com/user-attachments/assets/1fe7133a-c666-41ca-8757-09879e0db2dd)

**A megoldásod, ötleteid**
Legyen 610mm és 914mm a papír méret

**Miért lenne jó?**
Miliméter pontosan nyomtatunk

**Comment by Gilgames32** [comment]
utolsó releaseben javítva
