### ISSUE TITLE
Szélesség Magasság labelek

### ISSUE THREAD

**Issue by zsotroav** [Gilgames32/kbpr-ps#2]
**A probléma, mely felvetette az ötletet**
A script ablakét nézve csak lehetetlen eldönteni, hogy melyik mező a magasság és melyik a szélesség manuális méret állításkor

**A megoldásod, ötleteid**
Label a két inputbox mellé mint a margónál (also ahhoz a checkbox-hoz is egy ami nem tudom mit csinál)

**Miért lenne jó?**
UX += 100

**Egyéb**
Tényleg nem tudom mi az a checkbox

**Comment by Gilgames32** [comment]
aki tudja tudja

**Comment by Bende126** [comment]
Round checkbox? Xddd

*nemértek ui dizájnhoz*

**Comment by Gilgames32** [comment]
hogy mi o.o
