### ISSUE TITLE
Minimum nyomtatási méret

### ISSUE THREAD

**Issue by Bende126** [Gilgames32/kbpr-ps#4]
Megkeresem megkora, hátha írja az ezer akárhány oldalas kézikönyvben

**Comment by Bende126** [comment]
8 inch, 20.32 cm a minimum nyomtatási méret a kézikönyv szerint.

Szerintem nem kell enforceolni, csak infopultba kiírni h papírt fogsz pazarolni

**Comment by Gilgames32** [comment]
https://github.com/Gilgames32/kbpr-ps/commit/7b389d4d40e03ecca14de9913b3954bf16614bf0 commitban javítva.
Hozzáadtam egy extra popupot, ami megkérdezi, hogy biztos folytatni szeretnéd-e. Nem sokat teszteltem de valszeg jó.

**Comment by Bende126** [comment]
Full, működik
![image](https://github.com/Gilgames32/kbpr-ps/assets/28264530/7f312330-3bb2-4653-970d-15d338dc5f8c)

**Comment by Gilgames32** [comment]
gigászi
